---
AllCops:
  Exclude:
    - 'bin/nessana_old'

Layout/IndentHeredoc:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/Tab:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false
