---
AllCops:
  TargetRubyVersion: 2.4
  Exclude: []

Layout/IndentHeredoc:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/Tab:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
