---
language: ruby
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0

before_install:
  - gem install bundler --version 2.0.1

script:
  - cat config.yml.sample | tee config.yml
  - bundle exec rspec --format documentation
#  - bundle exec rubocop
